# Generated by Django 5.0.4 on 2025-05-09 00:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа груза')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы груза',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга доставки',
                'verbose_name_plural': 'Услуги доставки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('code', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Проведено')], max_length=50, verbose_name='Код статуса')),
                ('color', models.CharField(default='#FFFF00', max_length=7, verbose_name='Цвет статуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа упаковки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип упаковки',
                'verbose_name_plural': 'Типы упаковки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель транспорта',
                'verbose_name_plural': 'Модели транспорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('transport_number', models.CharField(max_length=50, verbose_name='Номер транспорта')),
                ('departure_datetime', models.DateTimeField(verbose_name='Время отправки')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Время доставки')),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Дистанция (км)')),
                ('departure_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес отправки')),
                ('arrival_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='delivery_files/%Y/%m/%d/', verbose_name='Медиафайл')),
                ('technical_condition', models.CharField(choices=[('good', 'Исправно'), ('bad', 'Неисправно')], default='good', max_length=10, verbose_name='Техническое состояние')),
                ('services', models.ManyToManyField(related_name='deliveries', to='api.deliveryservice', verbose_name='Услуги')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.deliverystatus', verbose_name='Статус доставки')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.packagetype', verbose_name='Тип упаковки')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.transportmodel', verbose_name='Модель транспорта')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-departure_datetime'],
            },
        ),
    ]
