# Generated by Django 5.0.4 on 2025-05-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystatus',
            name='code',
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название статуса'),
        ),
    ]
